spring:
  datasource:
    url: ${RAILWAY_DB_URL:jdbc:mysql://maglev.proxy.rlwy.net:26311/railway}
    username: ${RAILWAY_DB_USERNAME:root}
    password: ${RAILWAY_DB_PASSWORD:rZxdvZJcLFhWcLRfkHzkiDJFsUUgPQLx}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        # Đảm bảo Hibernate sử dụng múi giờ Việt Nam khi lưu vào database
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: "dd/MM/yyyy HH:mm:ss"
  mail:
    host: smtp.gmail.com
    port: 587
    username: "namhoang0505pro@gmail.com"
    password: "mzaz jytw mhcf ghci"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 87846938671-76pcjrb3ucf7ngmkai7b2qni7uvrn9qt.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
  # Đặt múi giờ mặc định cho JVM (bỏ spring.jvm.args vì không được hỗ trợ trực tiếp)
  # Thay vào đó, sẽ cấu hình qua biến môi trường hoặc lệnh chạy

jwt:
  signerKey: "3aF+lAiyA/tEAeeBtmlou0RwdTwXx0lU6SjH0MYBR7DRt9vyJzlv66uqnqHMP2NW"
  valid-duration: 3600
  refreshable-duration: 36000
beautya:
  feedback:
    link: http://localhost:8080/BookingService/api/feedbacks
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
booking:
  auto-cancel:
    minutes: 30